/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_networksecret_free: (a: number, b: number) => void;
export const networksecret_to_secret: (a: number) => number;
export const networksecret_to_proof: (a: number) => number;
export const networksecret_to_value: (a: number) => number;
export const __wbg_networkmixin_free: (a: number, b: number) => void;
export const networkmixin_new: (a: number, b: number, c: number) => number;
export const networkmixin_generate: (a: number, b: number) => number;
export const networkmixin_verify_proof: (a: number, b: number) => number;
export const networkmixin_verify_secret: (a: number, b: number) => number;
export const networkmixin_verify_proofs: (a: number, b: number) => number;
export const networkmixin_verify_secrets: (a: number, b: number) => number;
export const keccak256: (a: number) => number;
export const __wbg_keccak256hasher_free: (a: number, b: number) => void;
export const keccak256hasher_new: () => number;
export const keccak256hasher_clone: (a: number) => number;
export const keccak256hasher_update: (a: number, b: number) => void;
export const keccak256hasher_finalize: (a: number) => number;
export const base16_encode_lower: (a: number) => [number, number];
export const base16_encode_upper: (a: number) => [number, number];
export const base16_decode_mixed: (a: number, b: number) => [number, number, number];
export const base16_decode_lower: (a: number, b: number) => [number, number, number];
export const base16_decode_upper: (a: number, b: number) => [number, number, number];
export const __wbg_memory_free: (a: number, b: number) => void;
export const memory_new: (a: number, b: number) => number;
export const memory_ptr: (a: number) => number;
export const memory_len: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
